# Generated by Django 3.2.8 on 2021-10-21 01:14

import backend_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_code', models.CharField(max_length=8)),
                ('content', models.CharField(max_length=200)),
                ('answered', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_code', models.CharField(default=backend_api.models.get_unique_key, max_length=8, unique=True)),
                ('host', models.CharField(max_length=50, unique=True)),
                ('num_participants', models.IntegerField(default=0)),
                ('num_questions', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50, unique=True)),
                ('session_code', models.CharField(max_length=8)),
                ('is_host', models.BooleanField(default=False)),
            ],
        ),
    ]
